### PR TITLE
 #101 fixed bug for "more" tab swapping position

### PR DESCRIPTION
**Pull request by yoution**

### CODE REVIEW

**Comment by luizrrodrigues** [comment]
@yoution This was fixed?

**Comment by yoution** [comment]
@luizrrodrigues  https://monosnap.com/file/NdOOaVDmxE1PKvQ72PmKs4rovMiXtA
still has problem in your computer?

**Comment by luizrrodrigues** [comment]
@yoution Not reviewed yet, just confirming. :)

**Comment by luizrrodrigues** [comment]
@yoution I found an issue when "more" not showing.

Compete is moving the position in menu, check:

[Screen Recording 2020-01-17 at 21.06.40.mov.zip](https://github.com/topcoder-platform/navigation-component/files/4079738/Screen.Recording.2020-01-17.at.21.06.40.mov.zip)

**Comment by yoution** [comment]
@luizrrodrigues  to reproduce the problem , I want to show the more button, but it not show, I have make the screen very narrow， https://monosnap.com/file/Zx2vQMSpasW0oWZSYs71dsQa47ttSa

**Comment by luizrrodrigues** [comment]
@yoution I see, I'm able to see the "more" button.

What I'm mean is about when "more" button not showing the "compete" menu item is moving, this need be fixed.

**Comment by yoution** [comment]
@luizrrodrigues  https://github.com/topcoder-platform/navigation-component/pull/128 please review again

**Comment by yoution** [comment]
@luizrrodrigues  I don't  know, the 'more' button is not showed, even the screen is very narrow

**Comment by luizrrodrigues** [comment]
@yoution Ah okay, you mean in your side no able to see "more" button?

Have you try use Firefox?

**Comment by yoution** [comment]
@luizrrodrigues  firefox always show the 'more' button, chrome can not show the 'more' button even the screen is very narrow, I have pushed, please review

**Comment by luizrrodrigues** [comment]
@yoution Okay, I'll review and let you know. We already have a ticket to fix "more" always showing in Firefox.

**Pull request merged**
