### PR TITLE
Fix Issue 2396 - v2

### PR DESCRIPTION
**Pull request by ya3ya6**
Fix Issue 2396 - v2

### CODE REVIEW

**Comment by ya3ya6** [comment]
Pr updated. the conflict with "Highlight the current page" solved.

**Comment by ya3ya6** [comment]
@luizrrodrigues Pr updated. the conflict with "Highlight the current page" solved.

**Comment by luizrrodrigues** [comment]
@ya3ya6 Thanks

**Comment by ya3ya6** [comment]
Pr updated. changes: hiding level 3 menu in mobile.

**Pull request merged**
