### PR TITLE
Fix Issue #25

### PR DESCRIPTION
**Pull request by gets0ul**
https://github.com/topcoder-platform/community-app/issues/2403  
  
Fix the current selected item to be not clickable

### CODE REVIEW

**Comment by gets0ul** [comment]
@luizrrodrigues Updated.

**Comment by luizrrodrigues** [comment]
@gets0ul I think forced push not was a good way, please correct me if I'm wrong.

You just force-pushed to fix conflicts, but don't run re build `nom run build`, so /dist not include conflict fixed, right?

I asking this because looks like missing fix of other PR, please let me know.

Thanks.

**Comment by gets0ul** [comment]
I re run the build and pushed the new one against the old remote one. I had to use the force option as I rebased it on the latest develop so it won't cause conflict.

Just compare the commits. This PR only add 3 commits (my commits) to the latest develop branch (66 commits to 69).

**Comment by luizrrodrigues** [comment]
@gets0ul Following these steps:
- merge latest commits from `develop` to your code
- fix conflicts
- run `nom run build`
- push results

?

**Comment by gets0ul** [comment]
Yes, that's exactly what I did.  
The conflicts are only from both index.js files in dist folder as result of `npm run build`.  

I rebased my branch to the latest develop.
Ran the build.
And push the result.

But since my remote branch does not sync with the latest develop, the regular push won't work unless I used force option.

If you had any doubt, we can safely just close this PR and I can make a new clean PR.  
Thanks.

**Comment by luizrrodrigues** [comment]
@gets0ul Yes, please let close this one and create clean on.

Thanks.

**Comment by gets0ul** [comment]
New PR is made: https://github.com/topcoder-platform/navigation-component/pull/27

**Pull request closed without merging**
