### PR TITLE
Fix for issue#2519 

### PR DESCRIPTION
**Pull request by nahidshahin**
Close more button

### CODE REVIEW

**Comment by luizrrodrigues** [comment]
@nahidshahin Can you fix conflicts please?

**Comment by nahidshahin** [comment]
@luizrrodrigues done!

**Comment by nahidshahin** [comment]
@luizrrodrigues it's a bit difficult to fix this problem. Because two dropdown is part of two different component and it's parent component is in different project. So fixing and testing is a bit complex.

**Comment by luizrrodrigues** [comment]
https://github.com/topcoder-platform/community-app/pull/2624#pullrequestreview-249867543

**Pull request merged**
